services:
  accountsService:
   image: "bharat050/accounts:s4"
   container_name: accounts-ms
   ports:
    - "8080:8080"
   deploy:
    resources:
     limits:
      memory: 700m
   networks:
    - eazyBank
  loansService:
   image: "bharat050/loans:s4"
   container_name: loans-ms
   ports:
    - "8090:8090"
   deploy:
    resources:
     limits:
      memory: 700m
   networks:
    - eazyBank
  cardsService:
   image: "bharat050/cards:s4"
   container_name: cards-ms
   ports:
    - "9000:9000"
   deploy:
    resources:
     limits:
      memory: 700m
   networks:
    - eazyBank 
networks:
  eazyBank:
   driver: "bridge"