build:
 version: "1.0"
 
cards:
 message: "Welcome to the EazyBank CARDS related CONTACT info. PRODUCTION env docker"
 contactDetails: 
  name: "Manas - Product Manager"
  email: "manas@gmail.com"
 onCallSupport:
  (+91)- 1434567890
  (+91)- 1874567891