build:
 version: "1.0"
 
loans:
 message: "Welcome to the EazyBank loans related contact info. PRODUCTION env docker"
 contactDetails: 
  name: "Manas - Product Manager"
  email: "manas@gmail.com"
 onCallSupport:
  (+91)- 1434567890
  (+91)- 1874567891