build:
 version: "3.0"
 
loans:
 message: "Welcome to the EazyBank loans related contact info. IN DEV env"
 contactDetails: 
  name: "Bharat - Tech Lead"
  email: "bharat@gmail.com"
 onCallSupport:
  - "(+91)- 1234567890"
  - "(+91)- 1234567891"