build:
 version: "2.0"
 
loans:
 message: "Welcome to the EazyBank loans related CONTACT info. IN QA env"
 contactDetails: 
  name: "Rohit - QA Lead"
  email: "rohit@gmail.com"
 onCallSupport:
  (+91)- 12345662390
  (+91)- 12345635491