spring:
 application:
  name: "configServer"
 profiles:
#  active: git
    active: native
 cloud:
    config:
      server:
#       git:
#        uri: "https://github.com/eazybytes/eazybytes-config.git"
#        default-label: main
#        timeout: 5
#        clone-on-start: true
#        force-pull: true
        native:
#         search-locations: "file:///C://Users//bharat.yadav//Documents//config"
         search-locations: "classpath:/config" 
 rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"
  
encrypt:
 key: "24GHEIFVNXU57489DDSIVN48CNE89"

server:
  port: 8071 
  
management:
 endpoints:
  web:
   exposure:
    include: "*"
 health:
  readiness-state:
   enabled: true
  liveness-state:
   enabled: true
 endpoint:
  health:
   probes:
    enabled: true
