spring:
 config:
  activate:
   on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related Production Env APIs "
  contactDetails:
    name: "Satrou Gojo - Product Owner"
    email: "sgojo@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932