spring:
 config:
  activate:
   on-profile: "prod"

build:
 version: "1.0"
 
accounts:
 message: "Welcome to the EazyBanka ccount related contact info. PRODUCTION env"
 contactDetails: 
  name: "Manas - Product Manager"
  email: "manas@gmail.com"
 onCallSupport:
  (+91)- 1434567890
  (+91)- 1874567891